version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=authServer    
    ports:
      - "1234:1234"
    volumes:
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql   

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "brunoholandasilva@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "5432:80"
    depends_on:
      - postgres